import os
import json
from pathlib import Path
from dotenv import load_dotenv
from openai import OpenAI

# ==========================================
# LOAD ENVIRONMENT VARIABLES
# ==========================================

load_dotenv()

# ==========================================
# CONFIG
# ==========================================

TRANSCRIPTS_DIR = Path("call-data/transcripts")
ANALYSIS_DIR = Path("analysis")
INDIVIDUAL_DIR = ANALYSIS_DIR / "individual"

# สร้างโฟลเดอร์อัตโนมัติถ้ายังไม่มี
INDIVIDUAL_DIR.mkdir(parents=True, exist_ok=True)

# ตรวจสอบ OpenAI API Key
api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    print("ERROR: ไม่พบ OPENAI_API_KEY ในไฟล์ .env")
    raise SystemExit

client = OpenAI(api_key=api_key)

# ==========================================
# ANALYSIS PROMPT
# ==========================================

SYSTEM_PROMPT = """
You are an expert AI conversation analyst specializing in
Russian-language Voice AI agents and automated telephone systems.

You are analyzing telephone call transcripts generated by
competitor AI voice agents.

Your task is to reverse-engineer the conversational behavior,
decision logic, strengths, weaknesses, recurring patterns,
lead qualification methods, objection handling strategies,
and conversation flow of the competitor AI agent.

Analyze only information actually supported by the transcript.
Do not invent missing facts.

The transcript may contain speech recognition errors.
Use context carefully when interpreting unclear phrases.

Return valid JSON only using this exact structure:

{
    "summary": "",
    "opening_strategy": "",
    "conversation_goal": "",
    "conversation_flow": [],
    "questions_asked": [],
    "customer_intent": "",
    "customer_objections": [],
    "objection_handling": [],
    "qualification_logic": [],
    "closing_strategy": "",
    "agent_strengths": [],
    "agent_weaknesses": [],
    "naturalness_observations": [],
    "important_patterns": [],
    "implementation_insights": []
}

For implementation_insights, explain useful technical or conversational
lessons that could help design an original and improved Voice AI agent.
Do not copy proprietary wording verbatim.
"""

# ==========================================
# FIND TRANSCRIPTS
# ==========================================

transcript_files = sorted(TRANSCRIPTS_DIR.glob("*.txt"))

total = len(transcript_files)

print(f"\nพบ transcript ทั้งหมด {total} ไฟล์\n")

if total == 0:
    print("ERROR: ไม่พบไฟล์ .txt ใน call-data/transcripts")
    raise SystemExit

# ==========================================
# ANALYZE EACH TRANSCRIPT
# ==========================================

success_count = 0
skipped_count = 0
error_count = 0

for index, transcript_path in enumerate(transcript_files, start=1):

    output_path = INDIVIDUAL_DIR / f"{transcript_path.stem}.json"

    # ข้ามไฟล์ที่วิเคราะห์สำเร็จแล้ว
    if output_path.exists():
        print(
            f"[{index}/{total}] ข้าม {transcript_path.name} "
            f"(วิเคราะห์แล้ว)"
        )
        skipped_count += 1
        continue

    print(f"\n[{index}/{total}] กำลังวิเคราะห์: {transcript_path.name}")

    try:
        # อ่าน transcript
        transcript = transcript_path.read_text(
            encoding="utf-8",
            errors="replace"
        ).strip()

        if not transcript:
            print(f"ข้าม: {transcript_path.name} เป็นไฟล์ว่าง")
            skipped_count += 1
            continue

        # ส่งให้ OpenAI วิเคราะห์
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            response_format={
                "type": "json_object"
            },
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT
                },
                {
                    "role": "user",
                    "content": (
                        "Analyze the following Russian-language "
                        "competitor AI agent call transcript.\n\n"
                        f"FILE NAME: {transcript_path.name}\n\n"
                        "TRANSCRIPT:\n"
                        f"{transcript}"
                    )
                }
            ],
            temperature=0.2
        )

        result_text = response.choices[0].message.content

        if not result_text:
            raise ValueError("OpenAI returned an empty response")

        # ตรวจสอบว่าเป็น JSON จริง
        result = json.loads(result_text)

        # เพิ่มข้อมูลไฟล์ต้นทาง
        final_result = {
            "source_file": transcript_path.name,
            "analysis": result
        }

        # บันทึก JSON
        output_path.write_text(
            json.dumps(
                final_result,
                ensure_ascii=False,
                indent=2
            ),
            encoding="utf-8"
        )

        success_count += 1

        print(f"สำเร็จ: {output_path.name}")

    except KeyboardInterrupt:
        print("\n\nหยุดการทำงานโดยผู้ใช้")
        print("ไฟล์ที่วิเคราะห์เสร็จแล้วถูกบันทึกไว้เรียบร้อย")
        break

    except json.JSONDecodeError as e:
        error_count += 1
        print(f"JSON ERROR: {transcript_path.name}")
        print(e)

    except Exception as e:
        error_count += 1
        print(f"ERROR: {transcript_path.name}")
        print(e)

# ==========================================
# FINAL SUMMARY
# ==========================================

print("\n" + "=" * 50)
print("สรุปผลการวิเคราะห์")
print("=" * 50)

print(f"สำเร็จใหม่: {success_count}")
print(f"ข้ามไฟล์เดิม: {skipped_count}")
print(f"เกิดข้อผิดพลาด: {error_count}")
print(f"Transcript ทั้งหมด: {total}")

print("\nผลลัพธ์อยู่ที่:")
print("analysis/individual/")

print("\nเสร็จสิ้น!")