import os
import json
from pathlib import Path
from dotenv import load_dotenv
from openai import OpenAI

# ==========================================
# LOAD ENVIRONMENT VARIABLES
# ==========================================

load_dotenv()

# ==========================================
# CONFIG
# ==========================================

ANALYSIS_DIR = Path("analysis")
INDIVIDUAL_DIR = ANALYSIS_DIR / "individual"

COMPETITOR_OUTPUT = ANALYSIS_DIR / "competitor_analysis.json"
LOGIC_OUTPUT = ANALYSIS_DIR / "conversation_logic.json"
REPORT_OUTPUT = ANALYSIS_DIR / "intermediate_report.md"

api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    print("ERROR: ไม่พบ OPENAI_API_KEY ในไฟล์ .env")
    raise SystemExit

client = OpenAI(api_key=api_key)

# ==========================================
# LOAD INDIVIDUAL ANALYSIS FILES
# ==========================================

json_files = sorted(INDIVIDUAL_DIR.glob("*.json"))

total = len(json_files)

print(f"\nพบผลวิเคราะห์ทั้งหมด {total} ไฟล์")

if total == 0:
    print("ERROR: ไม่พบไฟล์ JSON ใน analysis/individual")
    raise SystemExit

all_analyses = []

for json_path in json_files:
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        all_analyses.append(data)

    except Exception as e:
        print(f"ERROR อ่านไฟล์ {json_path.name}: {e}")

print(f"โหลดสำเร็จ {len(all_analyses)} ไฟล์\n")

if not all_analyses:
    print("ERROR: ไม่มีข้อมูลที่สามารถนำไปวิเคราะห์ต่อได้")
    raise SystemExit


# ==========================================
# HELPER FUNCTION
# ==========================================

def ask_openai(system_prompt, user_prompt):

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        response_format={
            "type": "json_object"
        },
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ],
        temperature=0.2
    )

    content = response.choices[0].message.content

    if not content:
        raise ValueError("OpenAI returned an empty response")

    return json.loads(content)


# ==========================================
# PREPARE DATA
# ==========================================

analysis_data = json.dumps(
    all_analyses,
    ensure_ascii=False
)

print("กำลังวิเคราะห์ภาพรวม AI Agent คู่แข่ง...")


# ==========================================
# 1. COMPETITOR ANALYSIS
# ==========================================

competitor_system_prompt = """
You are a senior AI conversation analyst specializing in
Russian-language Voice AI agents and automated telephone systems.

You are given structured analyses of multiple telephone calls
generated by competitor AI voice agents.

Your task is to identify recurring patterns across all calls.

Analyze only information supported by the supplied data.
Do not invent facts.

Distinguish clearly between:
1. Patterns repeatedly observed across multiple calls.
2. Behaviors observed only occasionally.
3. Weaknesses and failures.
4. Implementation recommendations for building an original,
   improved Voice AI agent.

Return valid JSON only with this exact structure:

{
    "executive_summary": "",
    "recurring_opening_patterns": [],
    "recurring_conversation_flows": [],
    "common_questions": [],
    "common_customer_intents": [],
    "common_objections": [],
    "objection_handling_patterns": [],
    "qualification_patterns": [],
    "closing_patterns": [],
    "agent_strengths": [],
    "agent_weaknesses": [],
    "naturalness_patterns": [],
    "failure_patterns": [],
    "most_important_findings": [],
    "recommended_improvements": []
}
"""

competitor_result = ask_openai(
    competitor_system_prompt,
    (
        "Analyze the following structured results from "
        f"{len(all_analyses)} competitor AI agent calls:\n\n"
        + analysis_data
    )
)

with open(COMPETITOR_OUTPUT, "w", encoding="utf-8") as f:
    json.dump(
        competitor_result,
        f,
        ensure_ascii=False,
        indent=2
    )

print("สำเร็จ: competitor_analysis.json")


# ==========================================
# 2. CONVERSATION LOGIC
# ==========================================

print("\nกำลังสร้าง Conversation Logic สำหรับ AI Agent ของเรา...")


logic_system_prompt = """
You are a senior Voice AI conversation architect.

Using the supplied competitor analysis as research input,
design an original and improved conversation logic architecture
for a Russian-language Voice AI telephone agent.

Do not copy proprietary wording verbatim.

The goal is to create reusable conversational logic that can later
be implemented in a real-time AI voice agent.

The agent should:
- Speak naturally in Russian.
- Handle interruptions.
- Detect customer intent.
- Ask relevant qualification questions.
- Handle objections dynamically.
- Avoid repetitive robotic responses.
- Know when to continue, clarify, transfer, schedule follow-up,
  or end the call.
- Never invent customer information.
- Never claim an action was completed unless confirmed by the system.

Return valid JSON only using this exact structure:

{
    "agent_goal": "",
    "core_principles": [],
    "conversation_states": [],
    "opening_logic": {
        "goal": "",
        "actions": [],
        "transition_conditions": []
    },
    "qualification_logic": {
        "questions": [],
        "decision_rules": [],
        "transition_conditions": []
    },
    "intent_detection": {
        "intents": [],
        "signals": [],
        "actions": []
    },
    "objection_handling": {
        "objection_types": [],
        "response_strategy": [],
        "escalation_rules": []
    },
    "interruption_handling": {
        "rules": []
    },
    "silence_handling": {
        "rules": []
    },
    "transfer_logic": {
        "conditions": [],
        "actions": []
    },
    "follow_up_logic": {
        "conditions": [],
        "actions": []
    },
    "closing_logic": {
        "successful_close": [],
        "unsuccessful_close": [],
        "callback_close": []
    },
    "safety_rules": [],
    "memory_fields": [],
    "implementation_notes": []
}
"""

logic_result = ask_openai(
    logic_system_prompt,
    (
        "Create an original improved Voice AI conversation logic "
        "using this competitor analysis as research input:\n\n"
        + json.dumps(
            competitor_result,
            ensure_ascii=False
        )
    )
)

with open(LOGIC_OUTPUT, "w", encoding="utf-8") as f:
    json.dump(
        logic_result,
        f,
        ensure_ascii=False,
        indent=2
    )

print("สำเร็จ: conversation_logic.json")


# ==========================================
# 3. INTERMEDIATE REPORT
# ==========================================

print("\nกำลังสร้าง Intermediate Report...")


report_system_prompt = """
You are preparing a concise professional intermediate project report
for a client.

The project involves:
- Processing competitor AI voice agent recordings.
- Transcribing Russian-language calls.
- Analyzing recurring conversation patterns.
- Extracting conversation logic and implementation insights.
- Developing an improved Voice AI agent architecture.

Write a factual progress report based only on the supplied analysis.

Return valid JSON only with this structure:

{
    "title": "",
    "overview": "",
    "completed_work": [],
    "key_findings": [],
    "current_stage": "",
    "next_steps": []
}
"""

report_result = ask_openai(
    report_system_prompt,
    (
        "Create an intermediate project report using these results:\n\n"
        "COMPETITOR ANALYSIS:\n"
        + json.dumps(
            competitor_result,
            ensure_ascii=False
        )
        + "\n\nCONVERSATION LOGIC:\n"
        + json.dumps(
            logic_result,
            ensure_ascii=False
        )
    )
)

# ==========================================
# CONVERT REPORT JSON TO MARKDOWN
# ==========================================

markdown = f"""# {report_result.get('title', 'Intermediate Project Report')}

## Overview

{report_result.get('overview', '')}

## Completed Work

"""

for item in report_result.get("completed_work", []):
    markdown += f"- {item}\n"

markdown += "\n## Key Findings\n\n"

for item in report_result.get("key_findings", []):
    markdown += f"- {item}\n"

markdown += "\n## Current Stage\n\n"

markdown += report_result.get("current_stage", "")

markdown += "\n\n## Next Steps\n\n"

for item in report_result.get("next_steps", []):
    markdown += f"- {item}\n"

REPORT_OUTPUT.write_text(
    markdown,
    encoding="utf-8"
)

print("สำเร็จ: intermediate_report.md")


# ==========================================
# FINAL SUMMARY
# ==========================================

print("\n" + "=" * 55)
print("เสร็จสมบูรณ์!")
print("=" * 55)

print(f"""
สร้างไฟล์แล้ว:

1. {COMPETITOR_OUTPUT}
2. {LOGIC_OUTPUT}
3. {REPORT_OUTPUT}

ข้อมูลที่ใช้:
{len(all_analyses)} individual call analyses
""")